FROM node:boron

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

ADD ./package.json /app/package.json
WORKDIR /app
RUN yarn install

ADD ./src /app/src
RUN npm build

CMD npm start