FROM node:boron

RUN ln -s /usr/bin/node /usr/bin/nodejs
RUN apt-key adv --keyserver pgp.mit.edu --recv 9D41F3C3 && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install yarn

ADD ./package.json /app/package.json
WORKDIR /app
RUN yarn install

ADD ./src /app/src
RUN npm build

CMD npm start